### ISSUE TITLE
How about using --depth=1 on git clone?

### ISSUE THREAD

**Issue by imba-tjd** [lrinQVQ/script#14]
Can speed up

以及为什么libsodium要build from source呢？

**Comment by lrinQVQ** [comment]
https://github.com/jedisct1/libsodium/tree/master/src/libsodium/randombytes
https://github.com/jedisct1/libsodium/tree/stable/src/libsodium/randombytes

https://github.com/jedisct1/libsodium/tree/master/src/libsodium/crypto_aead
https://github.com/jedisct1/libsodium/tree/stable/src/libsodium/crypto_aead

对比下特性

**Comment by imba-tjd** [comment]
标题的建议怎么样呢

**Comment by lrinQVQ** [comment]
> 标题的建议怎么样呢

重写的过程中在考虑这个问题 但不知道会不会影响到 autoupdate功能中热修复的问题
