### ISSUE TITLE
debian 8.2 ss_install: 26

### ISSUE THREAD

**Issue by edidada** [lrinQVQ/script#3]
debian 8.2

Whether to deploy automatic updates?(yes/no) (default:yes): 
'/root/script/shadowsocks/bin' => '/root/script/dependencies/ss_update'
ln: failed to create hard link '/root/script/shadowsocks/bin': File exists
ln: failed to create hard link '/root/script/shadowsocks/bin': File exists
ln: failed to create hard link '/root/script/shadowsocks/bin': File exists
ln: failed to create hard link '/root/script/shadowsocks/bin': File exists
ln: failed to create hard link '/root/script/shadowsocks/bin': File exists
./ss_install: 26: .: Can't open /root/script/shadowsocks/bin/ss_config

**Comment by lrinQVQ** [comment]
get

**Comment by edidada** [comment]
I love QVQ forever!
